DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Adventure:MinNumberForGroup';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Adventure:MinNumberForGroup', '1', 'Minimum members for adventure group', 'Default 1. ', 'wa_', '2021-02-13 19:16:05');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Bots:AllowCamelCaseNames';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Bots:AllowCamelCaseNames', 'true', 'Allows the use of \'MyBot\' type names', 'Default false. ', 'wa_ ', '2021-02-13 19:21:46');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Bots:CasterStopMeleeLevel';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Bots:CasterStopMeleeLevel', '9', 'Level at which caster bots stop melee attacks', 'Default 13. ', 'wa_ ', '2021-02-13 19:21:52');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Bots:QuestableSpawnLimit';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Bots:QuestableSpawnLimit', 'true', 'Optional quest method to manage bot spawn limits using the quest_globals name bot_spawn_limit, see: /bazaar/Aediles_Thrall.pl', 'Default false. ', 'wa_ ', '2021-02-13 19:26:25');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Bots:QuestableSpells';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Bots:QuestableSpells', 'false', 'Anita Thrall\'s (Anita_Thrall.pl) Bot Spell Scriber quests', 'Default false.', 'wa_ ', '2021-03-21 15:23:33');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Character:EnableDiscoveredItems';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Character:EnableDiscoveredItems', 'true', 'If enabled, it enables EVENT_DISCOVER_ITEM and also saves character names and timestamps for the first time an item is discovered', 'Default false. ', 'wa_ ', '2021-02-13 19:31:28');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Character:EnableHungerPenalties';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Character:EnableHungerPenalties', 'true', 'Being hungry/thirsty has negative effects -- it does appear normal live servers do not have penalties', 'Default false. ', 'wa_ ', '2021-02-13 19:32:01');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Character:GroupExpMultiplier';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Character:GroupExpMultiplier', '0', 'The experience in a group is multiplied by this value in addition to the group multiplier. The group multiplier is: 2 members=x 1.2, 3=x1.4, 4=x1.6, 5=x1.8, 6=x2.16', 'Default 0.6499999761581. ', 'wa_ ', '2021-02-13 19:33:59');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Character:HealOnLevel';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Character:HealOnLevel', 'true', 'Setting whether a player should heal completely when leveling', 'Default false. ', 'wa_ ', '2021-02-13 19:34:42');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Character:MinStatusForNoDropExemptions';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Character:MinStatusForNoDropExemptions', '0', 'This allows status x and higher to trade no drop items', 'Default 80. ', 'wa_ ', '2021-02-13 19:38:49');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Combat:FleeGrayHPRatio';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Combat:FleeGrayHPRatio', '20', 'HP percentage when a Gray NPC begins to flee', 'Default 50. ', 'wa_ ', '2021-02-13 19:50:21');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Combat:FleeHPRatio';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Combat:FleeHPRatio', '20', 'HP percentage when a NPC begins to flee', 'Default 21. ', 'wa_', '2021-02-13 19:51:02');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Combat:MeleePush';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Combat:MeleePush', 'false', 'Eenable melee push', 'Default true.', 'wa_ ', '2021-02-13 19:52:13');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Combat:PetAttackMagicLevel';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Combat:PetAttackMagicLevel', '12', 'Level at which pets can cause magic damage', 'Default 30. ', 'wa_ ', '2021-02-13 19:53:32');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Inventory:AllowAnyWeaponTransformation';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Inventory:AllowAnyWeaponTransformation', 'true', 'Weapons can use any weapon transformation', 'Default false. ', 'wa_ ', '2021-02-13 19:57:55');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Pets:AttackCommandRange';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Pets:AttackCommandRange', '300.0000000000000', 'Range at which a pet will respond to attack commands', 'Default 200. ', 'wa_ ', '2021-02-13 20:04:22');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Pets:CanTakeNoDrop';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Pets:CanTakeNoDrop', 'true', 'Setting whether anyone can give no-drop items to pets', 'Default false. ', 'wa_ ', '2021-02-13 20:04:03');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Range:Say';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Range:Say', '170', 'The range that is required before /say or hail messages will work to an NPC', 'Default 135. ', 'wa_ ', '2021-02-13 20:06:41');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Skills:RequireTomeHandin';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Skills:RequireTomeHandin', 'true', 'Disable click-to-learn and force hand in to Guild Master', 'Default false. ', 'wa_ ', '2021-02-13 20:07:46');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Skills:SenseHeadingStartValue';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Skills:SenseHeadingStartValue', '0', 'Start value of sense heading skill', 'Default 200.', 'wa_ ', '2021-02-13 20:09:04');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Skills:SwimmingStartValue';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Skills:SwimmingStartValue', '1', 'Start value of swimming skill', 'Default 100. ', 'wa_ ', '2021-02-13 20:08:34');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='Skills:TrainSenseHeading';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'Skills:TrainSenseHeading', 'true', 'Switch whether SenseHeading is trained by use', 'Default false. ', 'wa_', '2021-02-13 20:08:59');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='World:ClearTempMerchantlist';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'World:ClearTempMerchantlist', 'false', 'Clears temp merchant items when world boots', 'Default true. ', 'wa_ ', '2021-02-13 20:16:43');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='World:FVNoDropFlag';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'World:FVNoDropFlag', '1', 'Sets the Firiona Vie settings on the client, allowing trading of no-drop items. 1=for all players, 2=for GM only', 'Default 0. ', 'wa_ ', '2021-02-13 20:18:26');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='World:MaxLevelForTutorial';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'World:MaxLevelForTutorial', '85', 'The highest level with which you can enter the tutorial', 'Default 15. ', 'wa_ ', '2021-02-19 11:42:36');
DELETE FROM `rule_values` WHERE `ruleset_id`=1 AND `rule_name`='World:MinOfflineTimeToReturnHome';
INSERT INTO `rule_values` (`ruleset_id`, `rule_name`, `rule_value`, `notes`, `wa_comments`, `wa_tags`, `wa_timestamp`) VALUES (1, 'World:MinOfflineTimeToReturnHome', '180', 'Minimum offline time to activate the Return Home button. 21600 seconds is 6 Hours', 'Default 21600. ', 'wa_ ', '2021-02-13 20:20:03');
