-- ---------------------------------------------------------------------------------------------
-- Author :		WarAngel
-- Created :		25Feb2021
-- ---------------------------------------------------------------------------------------------
-- Usage :		To add three columns to the database for referance and comments
-- 
-- 
-- ---------------------------------------------------------------------------------------------
	
ALTER TABLE `aa_ability`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `aa_ranks`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `aa_rank_effects`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `aa_rank_prereqs`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `account`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `account_flags`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `account_ip`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `account_rewards`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `adventure_details`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `adventure_members`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `adventure_stats`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `adventure_template`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `adventure_template_entry`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `adventure_template_entry_flavor`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `alternate_currency`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `auras`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `banned_ips`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `base_data`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `blocked_spells`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `books`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `bot_buffs`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bot_command_settings`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bot_data`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bot_groups`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bot_group_members`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bot_guild_members`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bot_heal_rotations`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bot_heal_rotation_members`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bot_heal_rotation_targets`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bot_inspect_messages`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bot_inventories`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bot_owner_options`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bot_pets`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bot_pet_buffs`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bot_pet_inventories`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bot_spells_entries`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bot_spell_casting_chances`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bot_stances`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bot_timers`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `bugs`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `bug_reports`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `buyer`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `character_activities`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_alternate_abilities`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_alt_currency`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_auras`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_bandolier`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_bind`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_buffs`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_corpses`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_corpse_items`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_currency`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_data`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_disciplines`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_enabledtasks`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_expedition_lockouts`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_inspect_messages`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_item_recast`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_languages`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_leadership_abilities`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_material`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_memmed_spells`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_pet_buffs`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_pet_info`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_pet_inventory`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_potionbelt`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_skills`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_spells`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_tasks`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `character_tribute`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `char_create_combinations`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `char_create_point_allocations`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `char_recipe_list`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `chatchannels`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `command_settings`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `completed_tasks`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `content_flags`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `damageshieldtypes`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `data_buckets`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `db_str`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `db_version`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `discovered_items`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `doors`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `dynamic_zones`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `eqtime`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `eventlog`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `expeditions`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `expedition_lockouts`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `expedition_members`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `faction_base_data`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `faction_list`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `faction_list_mod`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `faction_values`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `fishing`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `forage`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `friends`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `global_loot`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `gm_ips`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `goallists`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `graveyard`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `grid`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `grid_entries`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `ground_spawns`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `group_id`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `group_leaders`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `guilds`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `guild_bank`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `guild_members`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `guild_ranks`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `guild_relations`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `hackers`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `horses`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `instance_list`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `instance_list_player`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `inventory`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `inventory_snapshots`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `inventory_versions`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `ip_exemptions`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `items`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `item_tick`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `keyring`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `launcher`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `launcher_zones`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `ldon_trap_entries`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `ldon_trap_templates`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `level_exp_mods`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `lfguild`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `login_accounts`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `login_api_tokens`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `login_server_admins`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `login_server_list_types`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `login_world_servers`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `logsys_categories`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `lootdrop`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `lootdrop_entries`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `mail`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `merchantlist`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `name_filter`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `npc_emotes`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `npc_faction`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `npc_faction_entries`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `npc_scale_global_base`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `npc_spells`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `npc_spells_effects`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `npc_spells_effects_entries`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `npc_spells_entries`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `npc_types`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `npc_types_tint`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `object`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `object_contents`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `perl_event_export_settings`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `petitions`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `pets`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `pets_equipmentset`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `pets_equipmentset_entries`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `player_titlesets`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `profanity_list`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `proximities`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `qs_merchant_transaction_record`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `qs_merchant_transaction_record_entries`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `qs_player_aa_rate_hourly`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `qs_player_delete_record`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `qs_player_delete_record_entries`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `qs_player_events`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `qs_player_handin_record`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `qs_player_handin_record_entries`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `qs_player_move_record`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `qs_player_move_record_entries`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `qs_player_npc_kill_record`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `qs_player_npc_kill_record_entries`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `qs_player_speech`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `qs_player_trade_record`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `qs_player_trade_record_entries`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `quest_globals`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `raid_details`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `raid_leaders`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `raid_members`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `reports`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `respawn_times`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `rule_sets`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `rule_values`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `saylink`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `sharedbank`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `skill_caps`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `spawn2`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `spawnentry`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `spawngroup`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `spawn_conditions`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `spawn_condition_values`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `spawn_events`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `spells_new`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `spell_buckets`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `spell_globals`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `starting_items`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `start_zones`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `tasks`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `tasksets`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `task_activities`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `timers`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `titles`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `trader`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `trader_audit`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `tradeskill_recipe`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `tradeskill_recipe_entries`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `traps`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `tributes`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `tribute_levels`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `variables`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `veteran_reward_templates`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------

ALTER TABLE `zone`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `zone_flags`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `zone_points`
ADD COLUMN `wa_comments` TEXT NULL,
ADD COLUMN `wa_tags` TINYTEXT NULL,
ADD COLUMN `wa_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------------------------